;; DO NOT EDIT. RUN GENERATE TO REGENERATE

(in-package :cl-amqp)

(defconstant +amqp-port+ 5672)
(defconstant +amqp-frame-method+ 1)
(defconstant +amqp-frame-header+ 2)
(defconstant +amqp-frame-body+ 3)
(defconstant +amqp-frame-heartbeat+ 8)
(defconstant +amqp-frame-min-size+ 4096)
(defconstant +amqp-frame-end+ 206)
(defconstant +amqp-reply-success+ 200)
(defconstant +amqp-content-too-large+ 311)
(defconstant +amqp-no-route+ 312)
(defconstant +amqp-no-consumers+ 313)
(defconstant +amqp-access-refused+ 403)
(defconstant +amqp-not-found+ 404)
(defconstant +amqp-resource-locked+ 405)
(defconstant +amqp-precondition-failed+ 406)
(defconstant +amqp-connection-forced+ 320)
(defconstant +amqp-invalid-path+ 402)
(defconstant +amqp-frame-error+ 501)
(defconstant +amqp-syntax-error+ 502)
(defconstant +amqp-command-invalid+ 503)
(defconstant +amqp-channel-error+ 504)
(defconstant +amqp-unexpected-frame+ 505)
(defconstant +amqp-resource-error+ 506)
(defconstant +amqp-not-allowed+ 530)
(defconstant +amqp-not-implemented+ 540)
(defconstant +amqp-internal-error+ 541)
